### ISSUE TITLE
discussion

### ISSUE THREAD

**Issue by MaximKiselev** [Jxh98/XiaoMi-Ruby-15.6-2019#1]
hi. thanks for sharing. did u patch dsdt by yourself? on the standart conf or after add new wifi.
so i tried setup my laptop via that https://github.com/johnnync13/Xiaomi-Mi-Air/tree/master/EFI
i used that dsdt.
sound also does not work... alc 256 - layout 13 i think will be. need fix dsdt or patch applealc/codecommander kext.
ethernet - will be work by kext
wifi - used via usb wifi dongle
brightness/nightshift works good ... i did not add any kext.
also there is a problem with screen resolution... font a very small on hdpi... i think i can resolve via that https://www.tonymacx86.com/threads/release-hackintool-v2-3-8.254559/ to generate fix kext or https://github.com/daliansky/XiaoMi-Pro/tree/master/one-key-hidpi.
also i had some bug after upgrade to 10.14.4. notebook died in the middle of upgrade.

**Comment by Jxh98** [comment]
When I changed the configuration, I didn't patch DSDT.

The only big problem now is the built-in speakers.

You can use https://github.com/daliansky/XiaoMi-Pro/tree/master/one-key-hidpi to open hidpi and  fix UI size.
