### ISSUE TITLE
我发现我用这个也无限重启

### ISSUE THREAD

**Issue by zb2947244682** [Jxh98/XiaoMi-Ruby-15.6-2019#12]
机型没错，CPU，显卡都对得上。
我用黑果小冰都系统，全部装完后，替换EFI后，读条到一半就重启，不停重启。
用黑果小冰到EFI是提示:Please go to XXX panic XXX之类的。
是不是BIOS要设置什么？还是哪里操作有问题。

**Comment by Jxh98** [comment]
好吧 等我国庆休假的时候排查一下吧
你们可以先用 另外一位大佬的
[XenOriginal/XiaoMi-Ruby-15.6-UMA-only](https://github.com/XenOriginal/XiaoMi-Ruby-15.6-UMA-only)

**Comment by zb2947244682** [comment]
> 好吧 等我国庆休假的时候排查一下吧
> 你们可以先用 另外一位大佬的
> [XenOriginal/XiaoMi-Ruby-15.6-UMA-only](https://github.com/XenOriginal/XiaoMi-Ruby-15.6-UMA-only)

谢谢了~~~好奇怪这问题。。哈哈哈

**Comment by zb2947244682** [comment]
我怀疑是我没装DW1820A引起的这一系列问题
