### ISSUE TITLE
2018版ruby15.6，可以直接从10.13.6在线升级到10.14.4，但有一点问题

### ISSUE THREAD

**Issue by Mymetu** [Jxh98/XiaoMi-Ruby-15.6-2019#4]
二合一耳机麦克风插进去人声超级小，背景音正常，不带麦克风的小音响插上可以用，不过又一点杂音（可以忽略）。灰常感谢大佬的努力和无私奉献！

**Comment by Jxh98** [comment]
现在可以尝试更新一下，修正了部分问题。当然扬声器是别想了-。-||

**Comment by Mike-hd123** [comment]
> 二合一耳机麦克风插进去人声超级小，背景音正常，不带麦克风的小音响插上可以用，不过又一点杂音（可以忽略）。灰常感谢大佬的努力和无私奉献！

我的会无限重启怎么办
