### ISSUE TITLE
请问大佬这款怎么开启HiDPI？

### ISSUE THREAD

**Issue by JarvanKuo** [Jxh98/XiaoMi-Ruby-15.6-2019#5]
我也是2019款小米ruby，网上搜了一些开启HiDPI的方法，一键开启的那个没效果，使用hackintool开启http://bbs.pcbeta.com/viewthread-1805414-1-1.html可行，但是切换了分辨率后滚动屏幕会花屏，这个能解决不？大佬都是用什么方法开启HiDPI的？

**Comment by Jxh98** [comment]
https://github.com/Jxh98/XiaoMi-Ruby-15.6-2019/issues/1#issuecomment-491486837

**Comment by Jxh98** [comment]
[分辨率 选 2K](https://www.sqlsec.com/2018/09/hidpi.html)
